services:
  db:
    image: mysql:8.0
    container_name: autograde-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: autograde-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: LonSuddo-69
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
