"""Compare comment-retained vs comment-removed evaluation summaries.

This script supports NEXT_STEPS item #2 by producing a compact delta report for:
- overall metrics
- per-language metrics
- per-source metrics

Inputs are Phase 10 JSON summaries generated by scripts/evaluate_model.py.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.io import write_text


METRIC_KEYS = (
    "accuracy",
    "precision",
    "recall",
    "f1",
    "false_positive_rate",
    "false_negative_rate",
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare comment-ablation evaluation summaries.")
    parser.add_argument(
        "--with-comments",
        required=True,
        help="Path to the summary JSON from the comment-retained run.",
    )
    parser.add_argument(
        "--without-comments",
        required=True,
        help="Path to the summary JSON from the comment-removed run.",
    )
    parser.add_argument(
        "--output",
        default="artifacts/reports/comment_ablation_report.md",
        help="Output markdown report path.",
    )
    args = parser.parse_args()

    with_comments = _read_summary(PROJECT_ROOT / args.with_comments)
    without_comments = _read_summary(PROJECT_ROOT / args.without_comments)
    report = build_comment_ablation_report(
        with_comments=with_comments,
        without_comments=without_comments,
        with_comments_path=args.with_comments,
        without_comments_path=args.without_comments,
    )
    output_path = PROJECT_ROOT / args.output
    write_text(output_path, report)
    print(f"Wrote comment ablation report to {output_path}")


def build_comment_ablation_report(
    *,
    with_comments: dict[str, Any],
    without_comments: dict[str, Any],
    with_comments_path: str,
    without_comments_path: str,
) -> str:
    lines = [
        "# Comment-Retention Ablation Report",
        "",
        f"- With comments summary: `{with_comments_path}`",
        f"- Without comments summary: `{without_comments_path}`",
        "",
        "Delta columns are `without_comments - with_comments`.",
        "",
    ]
    lines.extend(
        _render_metric_delta_table(
            "Overall metrics",
            with_metrics=with_comments.get("overall_metrics", {}),
            without_metrics=without_comments.get("overall_metrics", {}),
        )
    )
    lines.extend(
        _render_group_delta_table(
            "Per-language deltas",
            with_groups=with_comments.get("per_language_metrics", {}),
            without_groups=without_comments.get("per_language_metrics", {}),
        )
    )
    lines.extend(
        _render_group_delta_table(
            "Per-source deltas",
            with_groups=with_comments.get("per_source_metrics", {}),
            without_groups=without_comments.get("per_source_metrics", {}),
        )
    )
    lines.extend(
        _render_group_delta_table(
            "Robustness slice deltas",
            with_groups=with_comments.get("robustness_slice_metrics", {}),
            without_groups=without_comments.get("robustness_slice_metrics", {}),
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def _render_metric_delta_table(title: str, *, with_metrics: dict[str, Any], without_metrics: dict[str, Any]) -> list[str]:
    lines = [f"## {title}", ""]
    lines.extend(
        [
            "| Metric | With comments | Without comments | Delta |",
            "|---|---:|---:|---:|",
        ]
    )
    for key in METRIC_KEYS:
        with_value = _as_float(with_metrics.get(key))
        without_value = _as_float(without_metrics.get(key))
        delta = without_value - with_value
        lines.append(
            f"| `{key}` | {_fmt(with_value)} | {_fmt(without_value)} | {_fmt_signed(delta)} |"
        )
    lines.append("")
    return lines


def _render_group_delta_table(
    title: str,
    *,
    with_groups: dict[str, Any],
    without_groups: dict[str, Any],
) -> list[str]:
    lines = [f"## {title}", ""]
    group_names = sorted(set(with_groups) | set(without_groups))
    if not group_names:
        lines.extend(["No overlapping group metrics available.", ""])
        return lines

    lines.extend(
        [
            "| Group | F1 (with) | F1 (without) | Delta F1 | FPR (with) | FPR (without) | Delta FPR | FNR (with) | FNR (without) | Delta FNR |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for group_name in group_names:
        with_metrics = with_groups.get(group_name, {})
        without_metrics = without_groups.get(group_name, {})
        with_f1 = _as_float(with_metrics.get("f1"))
        without_f1 = _as_float(without_metrics.get("f1"))
        with_fpr = _as_float(with_metrics.get("false_positive_rate"))
        without_fpr = _as_float(without_metrics.get("false_positive_rate"))
        with_fnr = _as_float(with_metrics.get("false_negative_rate"))
        without_fnr = _as_float(without_metrics.get("false_negative_rate"))
        lines.append(
            f"| `{group_name}` | {_fmt(with_f1)} | {_fmt(without_f1)} | {_fmt_signed(without_f1 - with_f1)} | "
            f"{_fmt(with_fpr)} | {_fmt(without_fpr)} | {_fmt_signed(without_fpr - with_fpr)} | "
            f"{_fmt(with_fnr)} | {_fmt(without_fnr)} | {_fmt_signed(without_fnr - with_fnr)} |"
        )
    lines.append("")
    return lines


def _read_summary(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Summary file not found: {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected a JSON object in summary file: {path}")
    return payload


def _as_float(value: Any) -> float:
    if value is None:
        return 0.0
    return float(value)


def _fmt(value: float) -> str:
    return f"{value:.4f}"


def _fmt_signed(value: float) -> str:
    return f"{value:+.4f}"


if __name__ == "__main__":
    main()
