# -*- coding: utf-8 -*-
"""TicTacToe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BfaABFgSVmy5jCRhDE22qyhXxBMhPtk

This implementation of TicTacToe uses the minmax algorithm to determine the best solution. The first version simply plays the game while the second show how the AI makes decisions on where to move next.
"""

import math

# Represents the game board
# We use indices 0-8 to correspond to the board positions:
# 0 | 1 | 2
# ---------
# 3 | 4 | 5
# ---------
# 6 | 7 | 8
board = [' ' for _ in range(9)]
HUMAN_PLAYER = 'X'
AI_PLAYER = 'O'

def print_board(current_board):
    """Prints the game board in a 3x3 grid."""
    print("")
    for i in range(0, 9, 3):
        print(f" {current_board[i]} | {current_board[i+1]} | {current_board[i+2]} ")
        if i < 6:
            print("---|---|---")
    print("")

def is_winner(bo, le):
    """Checks if a player has won."""
    # Check rows, columns, and diagonals
    return ((bo[0] == le and bo[1] == le and bo[2] == le) or
            (bo[3] == le and bo[4] == le and bo[5] == le) or
            (bo[6] == le and bo[7] == le and bo[8] == le) or
            (bo[0] == le and bo[3] == le and bo[6] == le) or
            (bo[1] == le and bo[4] == le and bo[7] == le) or
            (bo[2] == le and bo[5] == le and bo[8] == le) or
            (bo[0] == le and bo[4] == le and bo[8] == le) or
            (bo[2] == le and bo[4] == le and bo[6] == le))

def is_board_full(current_board):
    """Checks if the board is full (a draw)."""
    return ' ' not in current_board

def get_available_moves(current_board):
    """Returns a list of available move indices."""
    return [i for i, spot in enumerate(current_board) if spot == ' ']

def human_move():
    """Gets the human player's move and validates it."""
    while True:
        try:
            move = int(input("Enter your move (1-9): "))
            # Adjust to 0-8 index
            move -= 1
            if move >= 0 and move < 9:
                if board[move] == ' ':
                    return move
                else:
                    print("This spot is already taken! Please choose another.")
            else:
                print("Invalid move! Please enter a number between 1 and 9.")
        except ValueError:
            print("Invalid input! Please enter a number.")

def minimax(current_board, depth, is_maximizing):
    """
    Minimax algorithm implementation.
    - is_maximizing: True for AI (maximizer), False for Human (minimizer).
    """
    # Base cases: check for terminal states (win, lose, draw)
    if is_winner(current_board, AI_PLAYER):
        return 10
    if is_winner(current_board, HUMAN_PLAYER):
        return -10
    if is_board_full(current_board):
        return 0

    # --- Recursive Step ---
    if is_maximizing:
        # AI's turn (find the move with the highest score)
        best_score = -math.inf
        for move in get_available_moves(current_board):
            current_board[move] = AI_PLAYER
            score = minimax(current_board, depth + 1, False)
            current_board[move] = ' ' # Backtrack
            best_score = max(score, best_score)
        return best_score
    else:
        # Human's turn (find the move with the lowest score)
        best_score = math.inf
        for move in get_available_moves(current_board):
            current_board[move] = HUMAN_PLAYER
            score = minimax(current_board, depth + 1, True)
            current_board[move] = ' ' # Backtrack
            best_score = min(score, best_score)
        return best_score

def find_best_move(current_board):
    """
    Finds the best possible move for the AI.
    It iterates through all possible moves and uses the minimax function
    to score each one. It returns the move with the highest score.
    """
    best_score = -math.inf
    best_move = -1

    for move in get_available_moves(current_board):
        current_board[move] = AI_PLAYER
        # For the top-level call, we are the maximizer
        score = minimax(current_board, 0, False)
        current_board[move] = ' ' # Backtrack
        if score > best_score:
            best_score = score
            best_move = move

    return best_move

def main():
    """Main game loop."""
    print("Welcome to Tic Tac Toe!")
    print("You are 'X'. The AI is 'O'.")
    print_board([str(i+1) for i in range(9)]) # Show numbers for positions

    while True:
        # --- Human's Turn ---
        if not is_board_full(board):
            move = human_move()
            board[move] = HUMAN_PLAYER
            print_board(board)
            if is_winner(board, HUMAN_PLAYER):
                print("Congratulations! You win!")
                break
        else:
            print("It's a draw!")
            break

        # --- AI's Turn ---
        if not is_board_full(board):
            print("AI is thinking...")
            ai_move = find_best_move(board)
            board[ai_move] = AI_PLAYER
            print(f"AI chose position {ai_move + 1}.")
            print_board(board)
            if is_winner(board, AI_PLAYER):
                print("AI wins! Better luck next time.")
                break
        else:
            print("It's a draw!")
            break

if __name__ == "__main__":
    main()

"""TicTacToe version 2"""

import math
import time # Added for a small delay to make the AI's thinking more visible

# Represents the game board
# 0 | 1 | 2
# ---------
# 3 | 4 | 5
# ---------
# 6 | 7 | 8
board = [' ' for _ in range(9)]
HUMAN_PLAYER = 'X'
AI_PLAYER = 'O'

def print_board(current_board):
    """Prints the game board in a 3x3 grid."""
    print("")
    for i in range(0, 9, 3):
        print(f" {current_board[i]} | {current_board[i+1]} | {current_board[i+2]} ")
        if i < 6:
            print("---|---|---")
    print("")

def is_winner(bo, le):
    """Checks if a player has won."""
    # Check rows, columns, and diagonals
    return ((bo[0] == le and bo[1] == le and bo[2] == le) or
            (bo[3] == le and bo[4] == le and bo[5] == le) or
            (bo[6] == le and bo[7] == le and bo[8] == le) or
            (bo[0] == le and bo[3] == le and bo[6] == le) or
            (bo[1] == le and bo[4] == le and bo[7] == le) or
            (bo[2] == le and bo[5] == le and bo[8] == le) or
            (bo[0] == le and bo[4] == le and bo[8] == le) or
            (bo[2] == le and bo[4] == le and bo[6] == le))

def is_board_full(current_board):
    """Checks if the board is full (a draw)."""
    return ' ' not in current_board

def get_available_moves(current_board):
    """Returns a list of available move indices."""
    return [i for i, spot in enumerate(current_board) if spot == ' ']

def human_move():
    """Gets the human player's move and validates it."""
    while True:
        try:
            move = int(input("Enter your move (1-9): "))
            move -= 1 # Adjust to 0-8 index
            if 0 <= move < 9:
                if board[move] == ' ':
                    return move
                else:
                    print("This spot is already taken! Please choose another.")
            else:
                print("Invalid move! Please enter a number between 1 and 9.")
        except ValueError:
            print("Invalid input! Please enter a number.")

def minimax(current_board, depth, is_maximizing):
    """Minimax algorithm implementation (remains unchanged)."""
    if is_winner(current_board, AI_PLAYER):
        return 10
    if is_winner(current_board, HUMAN_PLAYER):
        return -10
    if is_board_full(current_board):
        return 0

    if is_maximizing:
        best_score = -math.inf
        for move in get_available_moves(current_board):
            current_board[move] = AI_PLAYER
            score = minimax(current_board, depth + 1, False)
            current_board[move] = ' '
            best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for move in get_available_moves(current_board):
            current_board[move] = HUMAN_PLAYER
            score = minimax(current_board, depth + 1, True)
            current_board[move] = ' '
            best_score = min(score, best_score)
        return best_score

# --- MODIFIED FUNCTION ---
def find_best_move(current_board):
    """
    Finds the best move for the AI and prints the evaluation process.
    """
    best_score = -math.inf
    best_move = -1

    print("--- AI is thinking... ---")
    print("Evaluating possible moves and their scores:")
    # Go through all possible moves
    for move in get_available_moves(current_board):
        # Place the AI's letter on the board for that move
        current_board[move] = AI_PLAYER
        # Calculate the score for that move assuming the opponent plays optimally
        score = minimax(current_board, 0, False)
        # Backtrack: undo the move so the board is clean for the next iteration
        current_board[move] = ' '

        # --- NEW: Print the score for the move being considered ---
        print(f"  - Move to position {move + 1} has a score of: {score}")

        # If this move's score is better than the best score found so far, update it
        if score > best_score:
            best_score = score
            best_move = move

    # --- NEW: Announce the chosen move ---
    print(f"\nConclusion: The best move is {best_move + 1} with a score of {best_score}")
    print("-------------------------")
    time.sleep(1) # Pause for a second to make it readable
    return best_move

def main():
    """Main game loop."""
    print("Welcome to Tic Tac Toe!")
    print("You are 'X'. The AI is 'O'.")
    print_board([str(i+1) for i in range(9)]) # Show numbers for positions

    while True:
        # --- Human's Turn ---
        if not is_board_full(board):
            move = human_move()
            board[move] = HUMAN_PLAYER
            print_board(board)
            if is_winner(board, HUMAN_PLAYER):
                print("Congratulations! You win!")
                break
        else:
            print("It's a draw!")
            break

        # --- AI's Turn ---
        if not is_board_full(board):
            ai_move = find_best_move(board)
            board[ai_move] = AI_PLAYER
            print(f"AI chose position {ai_move + 1}.")
            print_board(board)
            if is_winner(board, AI_PLAYER):
                print("AI wins! Better luck next time.")
                break
        else:
            print("It's a draw!")
            break

if __name__ == "__main__":
    main()