# -*- coding: utf-8 -*-
"""Simple Linear Regression Lab
Automatically generated by Colab.
Original file is located at
https://colab.research.google.com/drive/1FM0nr0vyebRFNFwvzyd07RKbgfFzlC0B
"""
# Simple Linear Regression Lab: Comparing Hyperparameters
# This lab will guide you through building a linear regression model from scratch,
# but with a new challenge: you will train five different models, each with
# its own unique combination of initial weights, biases, and learning rates.
# Your task is to fill in the code for the key functions (cost, gradient, and
# training loop) and then analyze how the different settings affect the final model performance.

# ----------------------------------------------------------------------------- 
# 1. Imports
# ----------------------------------------------------------------------------- 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------------- 
# 2. Acquire and Load Your Data
# ----------------------------------------------------------------------------- 
df = pd.read_csv("Salary_Data (1).csv")
X = df[['YearsExperience']].to_numpy()
y = df[['Salary']].to_numpy()

# ----------------------------------------------------------------------------- 
# 3. Plot the Data (for visualization)
# ----------------------------------------------------------------------------- 
plt.figure(figsize=(8, 6))
plt.scatter(X, y, color='blue', alpha=0.6)
plt.xlabel("Years of Experience", fontsize=15)
plt.ylabel("Salary", fontsize=15)
plt.title("Salary vs Years of Experience", fontsize=18)
plt.grid(True)
plt.show()

# ----------------------------------------------------------------------------- 
# 4. Implement Linear Regression from Scratch
# ----------------------------------------------------------------------------- 
def predict(X, w, b):
    return w * X + b

def compute_cost(y_pred, y_true):
    m = len(y_true)
    return (1 / (2 * m)) * np.sum((y_pred - y_true) ** 2)

def compute_gradient(X, y_pred, y_true):
    m = len(y_true)
    error = y_pred - y_true
    dw = (1 / m) * np.sum(error * X)
    db = (1 / m) * np.sum(error)
    return dw, db

# ----------------------------------------------------------------------------- 
# 5. Training Loop for Multiple Models
# ----------------------------------------------------------------------------- 
num_experiments = 5
initial_ws = np.random.randn(num_experiments, 1)
initial_bs = np.random.randn(num_experiments, 1)
learning_rates = [0.1, 0.05, 0.01, 0.005, 0.001]
epochs = 200
final_models = []

for i in range(num_experiments):
    print(f"\n--- Training Model {i+1} ---")
    w = initial_ws[i]
    b = initial_bs[i]
    lr = learning_rates[i]

    for epoch in range(epochs):
        y_pred = predict(X, w, b)
        cost = compute_cost(y_pred, y)
        dw, db = compute_gradient(X, y_pred, y)

        # Gradient descent update
        w -= lr * dw
        b -= lr * db

        # Optional: Print cost every 50 epochs
        if epoch % 50 == 0:
            print(f"Epoch {epoch}: Cost = {cost:.4f}")

    final_models.append({
        'w': w,
        'b': b,
        'lr': lr,
        'final_cost': cost,
        'predictions': predict(X, w, b)
    })

# ----------------------------------------------------------------------------- 
# 6. Plot the Final Results
# ----------------------------------------------------------------------------- 
plt.figure(figsize=(10, 8))
plt.scatter(X, y, label="Original Data", alpha=0.6)
for model in final_models:
    plt.plot(X, model['predictions'], label=f"LR={model['lr']}", linewidth=2)
plt.xlabel("Years of Experience", fontsize=15)
plt.ylabel("Salary", fontsize=15)
plt.title("Linear Regression Results (Multiple Learning Rates)", fontsize=18)
plt.legend()
plt.grid(True)
plt.show()

# ----------------------------------------------------------------------------- 
# 7. Check Your Final Parameters and Costs
# ----------------------------------------------------------------------------- 
for i, model in enumerate(final_models):
    print(f"\nModel {i+1} (LR={model['lr']})")
    print(f"Final w: {model['w'][0]:.4f}")
    print(f"Final b: {model['b'][0]:.4f}")
    print(f"Final Cost: {model['final_cost']:.4f}")

# Find best model (lowest cost)
best_model = min(final_models, key=lambda m: m['final_cost'])
print(f"\nBest Model → LR={best_model['lr']}, w={best_model['w'][0]:.2f}, b={best_model['b'][0]:.2f}, Cost={best_model['final_cost']:.2f}")

# Predict salary for 11 years of experience
years = 11
predicted_salary = predict(np.array([[years]]), best_model['w'], best_model['b'])
print(f"Predicted salary for {years} years of experience: ${predicted_salary[0][0]:.2f}")
